// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XGCHUSs8llW5Siajj-ng58WlGK5yXkM',
    appId: '1:118749808171:web:4835e4dd5795d81ef2cc6e',
    messagingSenderId: '118749808171',
    projectId: 'instagram-49bd8',
    authDomain: 'instagram-49bd8.firebaseapp.com',
    storageBucket: 'instagram-49bd8.appspot.com',
    measurementId: 'G-ZB3CW1M7SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUkOadKjX253wqJWlNBXhq3QJO0QuevM',
    appId: '1:118749808171:android:306c7f9a31f8f188f2cc6e',
    messagingSenderId: '118749808171',
    projectId: 'instagram-49bd8',
    storageBucket: 'instagram-49bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKFvWRE-ip_yL2NuPDZL9GzNPl51pSW3E',
    appId: '1:118749808171:ios:4933cba6eb6bfa79f2cc6e',
    messagingSenderId: '118749808171',
    projectId: 'instagram-49bd8',
    storageBucket: 'instagram-49bd8.appspot.com',
    iosClientId: '118749808171-6m7r8g53giejf3jbe44r462ue8v0iuv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
